before_commands:
    - "composer install --prefer-source"

tools:
    external_code_coverage:
        enabled: true
        timeout: 300
        filter:
            excluded_paths:
                - 'bin/*'
                - 'config/*'
                - 'templates/*'
                - 'var/*'
                - 'vendor/*'